//! Local task authority and IPC. Native execution is a separate integration boundary.
pub mod acceptance;
pub mod artifacts;
pub mod checks;
pub mod config;
pub mod doctor;
pub mod error;
pub mod export;
pub mod forge;
pub mod gateway;
pub mod host;
pub mod ipc;
pub mod mcp;
pub mod model;
pub mod platform;
pub mod policy;
mod redaction;
pub mod runtime;
pub mod scheduler;
pub mod store;
pub mod submission;
